### ISSUE TITLE
where is the link to log file ?

### ISSUE THREAD

**Issue by ashishsajwan** [jfhbrook/node-clf-parser#4]
how can u provide a path to log file...
if i have the log.txt with me and i want to run this parser on that log.txt .. how can i do it ?

**Comment by jfhbrook** [comment]
You can read in the log file with one of the `fs` functions, split it into lines (with `blob.split('\n')` if you load the whole thing into memory, otherwise with streams and the `split2` module on npm), and then pass each line to this function.

Cheers!
